(function() {
    const blackList = [
        "Chọc Tức Vợ Yêu - Mua Một Tặng Một",
        "Gió Ấm Không Bằng Anh Thâm Tình",
        "Tiểu yêu tinh của Bạc gia",
        "101 cách cua đổ đại lão hàng xóm",
        "Mãi là lần đầu",
        "Trăng trên đỉnh núi",
        "Để người hiểu thấu lòng tôi",
        "Sủng phi của Nhiếp Chính vương",
        "Mượn em một lần yêu",
        "Cô vợ thiên kim của tà thần",
        "Lấy chàng kỹ sư",
        "Cô vợ nhỏ của ngài Phó",
        "Sống lại trở thành đại lão giới khoa học",
        "Khi anh chạy về phía em",
        "Xuyên nhanh - Cứu rỗi nam phụ",
        "Ương ngạnh",
        "Trong họa có phúc",
        "Hôn nhân quyền lực",
        "Nhiếp chính vương diệt đào hoa",
        "Tổ điều tra đặc biệt",
        "Gió xuân rực lửa",
        "Đập nồi bán sắt đi học",
        "Kim phấn",
        "Bảo vệ siêu sao của tôi",
        "Siêu cấp cưng chiều",
        "Sơ Cửu của Lục Hào",
        "Bị ép lấy nam thần",
        "Đập nồi bán sắt đi học",
        "Mê hoặc anh đến nghiện",
        "Thiếu soái, chào anh!",
        "Nguyện cùng em đi qua gió sương",
        "Phượng hồ",
        "Và gió vẫn thì thầm tên em",
        "Triệu chứng chủ quan",
        "Mồi câu dịu dàng",
        "Bảo bối của ngài Tống",
        "Yêu tinh trong lòng anh",
        "Anh đến cùng ánh sao trời",
        "Thì ra boss thầm mến tôi",
        "Gấm hoa lồng son",
        "Niệm Tích",
        "Quyến rũ vô hạn",
        "Boss phản diện ngày ngày tìm đường chết",
        "Cô vợ minh tinh của tổng giám đốc",
        "Cẩm nang xử lý cực phẩm",
        "Đại Yến có một nữ thần thám",
        "Nhật ký xuyên nhanh của Du Lam",
        "Cục cưng ôm cái nào",
        "Bảo bối giá trên trời",
        "Tổ tông toàn năng sống lại",
        "Duyên âm nửa đêm",
        "Cứ yêu cứ chiều",
        "Kim phượng hoa đình",
        "Hoán đổi linh hồn",
        "Quán cà phê mèo",
        "Phương trình thanh xuân chờ giải",
        "Vương phi ngốc nghếch là đặc công",
        "Hôm nay Phó gia không giả vờ bệnh nữa",
        "Trùng sinh nuôi sói con",
        "Tình cũ không rủ cũng tới",
        "Yêu em như ngày đầu",
        "Yêu anh lính đặc chủng không quân",
        "Xương rồng nhỏ của Lục tiểu Xuyên",
        "Cuộc sống làm ruộng ở cổ đại",
        "Nhật ký tra nam hoàn lương",
        "Tung hoành trong lòng anh Tô",
        "Hóa ra em vẫn ở đây",
        "Ôm cây đợi thỏ",
        "Hướng về nơi anh",
        "Kế hoạch sinh tồn của đích nữ",
        "Ngài Cố thân mến",
        "Nữ phụ trở mình",
        "Hôn nhân trời định",
        "Tình yêu của pháo hôi",
        "Nữ phụ ở mạt thế",
        "Nợ âm phải trả",
        "Mật mã nước Cổ Thục",
        "Lại trở thành phu nhân tướng quân",
        "Phú bà khi yêu",
        "Quỷ giáng lâm: Chồng ma thích trêu ghẹo",
        "Yêu em bằng cả trái tim",
        "Trùng sinh làm giàu ở cổ đại",
        "Yêu lại từ đầu",
        "Hoa thần lục",
        "Từng đóa bọt sóng",
        "Cám dỗ ngọt ngào",
        "Xin chào thiếu tướng đại nhân",
        "Tuyệt sủng âm hôn",
        "Nghề phò mã",
        "Này buông cô ấy ra",
        "Lưu manh đi lấy vợ",
        "Phủ sinh Cô mộ Triều tịch",
        "Tình đầu dấu yêu",
        "Mousse - Đánh thức miền yêu",
        "Anh có thiếu người yêu không?",
        "Gió Nam hiểu lòng tôi",
        "Lật Hạ ký",
        "Mạnh mẽ là em dịu dàng là anh",
        "Khi tình yêu chớm nở",
        "Cô vợ hung tàn của Quyền thiếu",
        "Hào môn gả hào môn",
        "Nhật ký làm ruộng ở thôn Trường Thủy",
        "Tân An Quỷ Sự",
        "Bản hòa tấu hôn nhân",
        "Đánh cắp trái tim anh",
        "Đến phủ Khai Phong làm nhân viên công vụ",
        "Dụ hôn",
        "Hoắc gia, phu nhân lại đi xem bói rồi",
        "Năm đầu tiên khi tôi 30",
        "Thế tử phi cá muối",
        "Tôi như ánh dương rạng rỡ",
        "Trùng sinh, tôi nhặt được chàng cơ trưởng",
        "Hiệu sách đêm khuya",
        "Yêu thầm kẻ sát nhân nhà bên",
        "Lạc mất cô dâu xung hỉ",
        "Thiên đường có em",
        "Yêu em bằng cả sinh mệnh",
        "Pháp y ma cà rồng",
        "Nhật ký hắc hóa của bạch nguyệt quang",
        "Giữa chốn phồn hoa gặp được người",
        "Cuộc sống trà xanh của Thái tử điện hạ",
        "Hôm nay thiên kim lại đi vả mặt",
        "Nam chính bệnh kiều cầu cưng chiều",
        "10 vạn lý do phải bơm vàng",
        "Tình yêu phi thường",
        "Đông Phương mỹ nhân",
        "Trấn Hồn Quan",
        "Mặt trời không lặn về tây",
        "Xin em ở lại bên anh",
        "Đoán xem anh yêu em nhường nào",
        "Anh có thiếu người yêu không?",
        "Dệt ngân hà cho em",
        "Trêu chọc vượt giới",
        "Bỉ Ngạn đơm hương",
        "Vợ yêu là đại lão",
        "Yêu nhau rồi cũng trở về với nhau",
        "Người đàn ông của tôi",
        "Họa đến rồi, mời thanh toán!",
        "Tôi và bạn trai kinh tế",
        "Đông Chí",
        "Một đời chỉ cần có em",
        "Hải Thượng phồn hoa",
        "Hạ mạch 86 độ",
        "Vứt bỏ trái tim mong manh",
        "Đừng phiền tôi học tập - Học tã chính là học tã",
        "Bà Bùi, em đã kết hôn",
        "Đồ đệ nhà ta lại tèo rồi",
        "Y phẩm phong hoa",
        "Làm màu ký",
        "Ngàn năm tương tư",
        "Nam Thành chờ trăng về",
        "Vứt bỏ anh là điều dũng cảm nhất",
        "Xuyên nhanh: Dân chơi số 1",
        "Thiên hậu tiểu thanh mai",
        "Thất Duyên Kiếp",
        "Cách một cánh cửa",
        "Yêu tinh quán",
        "Pháo hôi ư ư đại lão",
        "Doanh môn phục quý",
        "Em là cả nhân gian của anh",
        "Thiên hậu trở về",
        "Chỉ yêu mình em",
        "Ảnh đế thị phi",
        "Thịnh thế kiều y",
        "Đông Túy Hạ Hàm",
        "Người trong mộng",
        "Xuyên nhanh: Nhiệm vụ Ái Hồn",
        "Người dấu yêu",
        "Tiểu thư hầu phủ",
        "Ấm áp có em, ngọt ngào có anh",
        "Cẩm đường quy yến",
        "Nông viên tự cẩm",
        "Mai trắng trong tuyết",
        "Nhà cung cấp cẩu lương",
        "Hắc thiên kim",
        "Uông xưởng công",
        "Cưng chiều cô vợ quân nhân",
        "Oan gia độc miệng",
        "Nữ vương thời thượng",
        "Thiên kim báo thù",
        "Ấn Công Đức",
        "Văn phòng Phấn Hồng",
        "Hứa với em một đời hoa nở",
        "Cưng chiều cô vợ đanh đá",
        "Đám cưới hào môn",
        "Nhật ký trở thành Boss thời mạt thế",
        "Thịnh thế hôn nhân",
        "Gặp đúng lúc, yêu đúng người",
        "Nhất sinh nhất thế: Tiếu thương khung",
        "Nhặt được vương phi tham tiền",
        "Vợ boss là công chúa",
        "Bổ Thiên Ký",
        "Tình đắng",
        "Quân hôn chớp nhoáng",
        "Nhật ký trưởng thành của Nữ Oa",
        "Điền viên cẩm tú",
        "Nhật ký sa lầy",
        "Có người đang tìm bạn",
        "Lấy chồng quyền thế",
        "Thực tập sinh thần tượng",
        "Nhật ký cua trai của Nữ phụ",
        "Phượng Kinh Thiên",
        "Công tước",
        "Xin chào, người thừa kế",
        "Xin lỗi em chỉ là con đĩ",
        "Yêu anh hơn cả tử thần",
        "Du Thái Hoa",
        "Mật ngọt hôn nhân",
        "Vạn kiếp yêu em",
        "Người đẹp phải mạnh mẽ",
        "Người anh yêu",
        "Nghe kìa thời gian đang hát",
        "Thành Duy Lạc",
        "Thiên kim đại chiến",
        "Trời đất tác thành",
        "Tường vi đêm đầu tiên",
        "Một nửa yêu thương",
        "Mandarin của tôi",
        "Gấu ơi, giúp anh!",
        "Em là vì sao trong mắt anh",
        "Sự dịu dàng chết tiệt",
        "Sổ tay hình cảnh",
        "Sẽ có thiên thần thay anh yêu em",
        "Quên để hạnh phúc",
        "Quân tử chi giao",
        "Phút giây gặp gỡ một đời bên nhau",
        "Cô bạn gái nhút nhát của tôi",
        "Cặp đôi hoàn cảnh",
        "Cửu thiên khuynh ca",
        "Xà vương quấn thân: Bà xã, sinh quả trứng!",
        "Nàng dâu cực phẩm",
        "Nhất sinh nhất thế: Tiếu Hồng Trần",
        "Sinh con thời mạt thế",
        "Hệ thống livestream của Nữ Đế",
        "Kế hoạch theo đuổi vợ yêu",
        "Chạy đâu cho thoát",
        "Bẫy hôn nhân: Vợ trước ôm con chạy",
        "Chào buổi sáng: Ông xã cool ngầu",
        "Thục thiên mộng hoa lục",
        "Liệt Hỏa Như Ca",
        "Bí mật vượt thời gian",
        "Xin em đứng đắn chút",
        "Bên nhau trọn đời",
        "Văn sĩ điên cuồng",
        "Đêm của anh, ngày của em",
        "Giường đàn bà",
        "Hẹn ước nơi thiên đường",
        "Đại chiến mẹ chồng nàng dâu",
        "Mẹ chồng quyền thế của tôi",
        "Kết hôn chớp nhoáng",
        "Quân hôn chớp nhoáng",
        "Giây phút này thuộc về chúng ta",
        "Tình yêu bên trái",
        "Tình yêu điên cuồng",
        "Chỉ yêu cây kẹo bông nhỏ",
        "Tình yêu nơi đâu",
        "Thẻ đọc tâm",
        "Sự nhầm lẫn tai hại",
        "Mùa đông ấm áp",
        "Nhật ký chạy trốn tình yêu",
        "Thiên thần sa ngã",
        "Xem như anh lợi hại, đồ xấu xa!",
        "Bài học yêu của tiểu ma vương",
        "Trước là tiểu nhân, sau là quân tử",
        "Không thể quên em",
        "Khi tình yêu đến lần nữa",
        "Tình yêu đau dạ dày",
        "Lễ tình nhân đến muộn",
        "Duyên nợ đào hoa",
        "Bài học yêu của tiểu ma vương",
        "Khách điếm Đại Long Môn",
        "Thái tử phi thăng chức ký",
        "Phiêu du giang hồ",
        "Năm tháng là đóa lưỡng sinh hoa",
        "Nhật ký dạy chồng của hổ cái",
        "Xem như anh lợi hại, đồ xấu xa!",
        "Ba kiếp dây dưa cửu vĩ hồ",
        "Một mối tương tư",
        "Chỉ vì phút giây được gặp em",
        "Nhất phẩm thiên kim",
        "Chạy đâu cho thoát",
        "Hôn nhân đã qua",
        "Thất dạ đàm",
        "Em là đôi cánh của anh",
        "Lan Lăng Vương",
        "Em đồng ý gọi anh là chồng",
        "Ảnh hậu tái sinh",
        "Tướng quân ở trên, ta ở dưới",
        "Vì em gặp anh",
        "Hôn lên đôi môi Peter Pan",
        "Tháng ngày ta đã qua",
        "Ở lại nơi này cùng anh",
        "Hảo mộc vọng thiên",
        "Trầm Hương Uyển",
        "Đại thần em nuôi anh",
        "Boss hung mãnh 2: Cả đời chỉ vì em",
        "Không chỉ trong lời nói",
        "Thử ly hôn",
        "Nếu như có một ngày",
        "Dựa vào hơi ấm của em",
        "Mong rằng hoa vẫn đỏ",
        "Vận đào hoa của Tiểu Mật",
        "Hoài niệm",
        "Quyết ý đi cùng anh",
        "Nửa đường xuất giá",
        "Tình yêu còn mãi",
        "Cô chủ nhỏ xinh đẹp của tôi",
        "Boss là nữ phụ: Thiên kim hào môn",
        "Không cẩn thận, họa lớn rồi!",
        "Nét cười nơi ấy",
        "Thất gia",
        "Dư vị trà chiều",
        "Boss hung mãnh: Ông xã, kết hôn nào!",
        "Trăng đêm",
        "Hoài niệm",
        "Quán cà phê XY",
        "Nữ tặc Giang Bắc",
        "Bí mật vượt thời gian",
        "Chọc tức vợ yêu - Mua một tặng một",
        "Yêu thương trao anh",
        "Hy du ký",
        "Này, buông cô ấy ra!",
        "Chuyện dũng cảm nhất",
        "Thiên Vương",
        "Hạnh phúc không ngừng",
        "Thùng cơm sát vách",
        "Thục thiên mộng hoa lục",
        "Ánh sao ban ngày",
        "Phấn hoa lầu xanh",
        "Hướng về trái tim",
        "Yêu em bằng cả trái tim anh",
        "Thành đô đêm nay hãy để tôi một mình",
        "Mị Hương",
        "Phiêu du giang hồ",
        "Hảo mộc vọng thiên",
        "Đại thần em nuôi anh",
        "Lập thệ thành yêu",
        "Dạo bước phồn hoa",
        "Nếu thanh xuân không giữ lại được",
        "Liên hoa yêu cốt"
    ];
    
    try {
        let jsonText = document.documentElement.innerText.replace(/[\u0000-\u001F\u007F-\u009F]/g, "");
        let json = JSON.parse(jsonText);

        let next = null;
        if (json.pager.page < json.pager.total_count) {
            next = json.pager.page + 1;
        }

        let novelList = [];
        for (let i = 0; i < json.data.length; i++) {
            const name = json.data[i].NAME;
            if (
                name &&
                !blackList.some(b => b.toLowerCase() === name.toLowerCase())
            ) {
                novelList.push({
                    name: name,
                    link: json.data[i].ID,
                    description: json.data[i].AUTHOR,
                    cover: json.data[i].THUMB,
                    host: "http://api.mottruyen.com"
                })
            }
            
        }

        return JSON.stringify({ success: true, data: novelList, next: next });
    } catch (error) {
        return JSON.stringify({ success: false, error: error.message });
    }
})()
