(function() {
    const blackList = [
        "Thủ tướng mời xem đơn ly hôn",
        "Chọc Tức Vợ Yêu Mua Một Tặng Một",
        "Gió Ấm Không Bằng Anh Thâm Tình",
        "Tiểu yêu tinh của Bạc gia",
        "101 cách cua đổ đại lão hàng xóm",
        "Mãi là lần đầu",
        "Trăng trên đỉnh núi",
        "Để người hiểu thấu lòng tôi",
        "Sủng phi của Nhiếp Chính vương",
        "Mượn em một lần yêu",
        "Cô vợ thiên kim của tà thần",
        "Lấy chàng kỹ sư",
        "Cô vợ nhỏ của ngài Phó",
        "Sống lại trở thành đại lão giới khoa học",
        "Khi anh chạy về phía em",
        "Xuyên nhanh Cứu rỗi nam phụ",
        "Ương ngạnh",
        "Trong họa có phúc",
        "Hôn nhân quyền lực",
        "Nhiếp chính vương diệt đào hoa",
        "Tổ điều tra đặc biệt",
        "Gió xuân rực lửa",
        "Đập nồi bán sắt đi học",
        "Kim phấn",
        "Bảo vệ siêu sao của tôi",
        "Siêu cấp cưng chiều",
        "Sơ Cửu của Lục Hào",
        "Bị ép lấy nam thần",
        "Đập nồi bán sắt đi học",
        "Mê hoặc anh đến nghiện",
        "Thiếu soái chào anh",
        "Nguyện cùng em đi qua gió sương",
        "Phượng hồ",
        "Và gió vẫn thì thầm tên em",
        "Triệu chứng chủ quan",
        "Mồi câu dịu dàng",
        "Bảo bối của ngài Tống",
        "Yêu tinh trong lòng anh",
        "Anh đến cùng ánh sao trời",
        "Thì ra boss thầm mến tôi",
        "Gấm hoa lồng son",
        "Niệm Tích",
        "Quyến rũ vô hạn",
        "Boss phản diện ngày ngày tìm đường chết",
        "Cô vợ minh tinh của tổng giám đốc",
        "Cẩm nang xử lý cực phẩm",
        "Đại Yến có một nữ thần thám",
        "Nhật ký xuyên nhanh của Du Lam",
        "Cục cưng ôm cái nào",
        "Bảo bối giá trên trời",
        "Tổ tông toàn năng sống lại",
        "Duyên âm nửa đêm",
        "Cứ yêu cứ chiều",
        "Kim phượng hoa đình",
        "Hoán đổi linh hồn",
        "Quán cà phê mèo",
        "Phương trình thanh xuân chờ giải",
        "Vương phi ngốc nghếch là đặc công",
        "Hôm nay Phó gia không giả vờ bệnh nữa",
        "Trùng sinh nuôi sói con",
        "Tình cũ không rủ cũng tới",
        "Yêu em như ngày đầu",
        "Yêu anh lính đặc chủng không quân",
        "Xương rồng nhỏ của Lục tiểu Xuyên",
        "Cuộc sống làm ruộng ở cổ đại",
        "Nhật ký tra nam hoàn lương",
        "Tung hoành trong lòng anh Tô",
        "Hóa ra em vẫn ở đây",
        "Ôm cây đợi thỏ",
        "Hướng về nơi anh",
        "Kế hoạch sinh tồn của đích nữ",
        "Ngài Cố thân mến",
        "Nữ phụ trở mình",
        "Hôn nhân trời định",
        "Tình yêu của pháo hôi",
        "Nữ phụ ở mạt thế",
        "Nợ âm phải trả",
        "Mật mã nước Cổ Thục",
        "Lại trở thành phu nhân tướng quân",
        "Phú bà khi yêu",
        "Quỷ giáng lâm Chồng ma thích trêu ghẹo",
        "Yêu em bằng cả trái tim",
        "Trùng sinh làm giàu ở cổ đại",
        "Yêu lại từ đầu",
        "Hoa thần lục",
        "Từng đóa bọt sóng",
        "Cám dỗ ngọt ngào",
        "Xin chào thiếu tướng đại nhân",
        "Tuyệt sủng âm hôn",
        "Nghề phò mã",
        "Này buông cô ấy ra",
        "Lưu manh đi lấy vợ",
        "Phủ sinh Cô mộ Triều tịch",
        "Tình đầu dấu yêu",
        "Mousse Đánh thức miền yêu",
        "Anh có thiếu người yêu không?",
        "Gió Nam hiểu lòng tôi",
        "Lật Hạ ký",
        "Mạnh mẽ là em dịu dàng là anh",
        "Khi tình yêu chớm nở",
        "Cô vợ hung tàn của Quyền thiếu",
        "Hào môn gả hào môn",
        "Nhật ký làm ruộng ở thôn Trường Thủy",
        "Tân An Quỷ Sự",
        "Bản hòa tấu hôn nhân",
        "Đánh cắp trái tim anh",
        "Đến phủ Khai Phong làm nhân viên công vụ",
        "Dụ hôn",
        "Hoắc gia phu nhân lại đi xem bói rồi",
        "Năm đầu tiên khi tôi 30",
        "Thế tử phi cá muối",
        "Tôi như ánh dương rạng rỡ",
        "Trùng sinh tôi nhặt được chàng cơ trưởng",
        "Hiệu sách đêm khuya",
        "Yêu thầm kẻ sát nhân nhà bên",
        "Lạc mất cô dâu xung hỉ",
        "Thiên đường có em",
        "Yêu em bằng cả sinh mệnh",
        "Pháp y ma cà rồng",
        "Nhật ký hắc hóa của bạch nguyệt quang",
        "Giữa chốn phồn hoa gặp được người",
        "Cuộc sống trà xanh của Thái tử điện hạ",
        "Hôm nay thiên kim lại đi vả mặt",
        "Nam chính bệnh kiều cầu cưng chiều",
        "10 vạn lý do phải bơm vàng",
        "Tình yêu phi thường",
        "Đông Phương mỹ nhân",
        "Trấn Hồn Quan",
        "Mặt trời không lặn về tây",
        "Xin em ở lại bên anh",
        "Đoán xem anh yêu em nhường nào",
        "Anh có thiếu người yêu không?",
        "Dệt ngân hà cho em",
        "Trêu chọc vượt giới",
        "Bỉ Ngạn đơm hương",
        "Vợ yêu là đại lão",
        "Yêu nhau rồi cũng trở về với nhau",
        "Người đàn ông của tôi",
        "Họa đến rồi mời thanh toán",
        "Tôi và bạn trai kinh tế",
        "Đông Chí",
        "Một đời chỉ cần có em",
        "Hải Thượng phồn hoa",
        "Hạ mạch 86 độ",
        "Vứt bỏ trái tim mong manh",
        "Đừng phiền tôi học tập Học tã chính là học tã",
        "Bà Bùi em đã kết hôn",
        "Đồ đệ nhà ta lại tèo rồi",
        "Y phẩm phong hoa",
        "Làm màu ký",
        "Ngàn năm tương tư",
        "Nam Thành chờ trăng về",
        "Vứt bỏ anh là điều dũng cảm nhất",
        "Xuyên nhanh Dân chơi số 1",
        "Thiên hậu tiểu thanh mai",
        "Thất Duyên Kiếp",
        "Cách một cánh cửa",
        "Yêu tinh quán",
        "Pháo hôi ư ư đại lão",
        "Doanh môn phục quý",
        "Em là cả nhân gian của anh",
        "Thiên hậu trở về",
        "Chỉ yêu mình em",
        "Ảnh đế thị phi",
        "Thịnh thế kiều y",
        "Đông Túy Hạ Hàm",
        "Người trong mộng",
        "Xuyên nhanh Nhiệm vụ Ái Hồn",
        "Người dấu yêu",
        "Tiểu thư hầu phủ",
        "Ấm áp có em ngọt ngào có anh",
        "Cẩm đường quy yến",
        "Nông viên tự cẩm",
        "Mai trắng trong tuyết",
        "Nhà cung cấp cẩu lương",
        "Hắc thiên kim",
        "Uông xưởng công",
        "Cưng chiều cô vợ quân nhân",
        "Oan gia độc miệng",
        "Nữ vương thời thượng",
        "Thiên kim báo thù",
        "Ấn Công Đức",
        "Văn phòng Phấn Hồng",
        "Hứa với em một đời hoa nở",
        "Cưng chiều cô vợ đanh đá",
        "Đám cưới hào môn",
        "Nhật ký trở thành Boss thời mạt thế",
        "Thịnh thế hôn nhân",
        "Gặp đúng lúc yêu đúng người",
        "Nhất sinh nhất thế Tiếu thương khung",
        "Nhặt được vương phi tham tiền",
        "Vợ boss là công chúa",
        "Bổ Thiên Ký",
        "Tình đắng",
        "Quân hôn chớp nhoáng",
        "Nhật ký trưởng thành của Nữ Oa",
        "Điền viên cẩm tú",
        "Nhật ký sa lầy",
        "Có người đang tìm bạn",
        "Lấy chồng quyền thế",
        "Thực tập sinh thần tượng",
        "Nhật ký cua trai của Nữ phụ",
        "Phượng Kinh Thiên",
        "Công tước",
        "Xin chào người thừa kế",
        "Xin lỗi em chỉ là con đĩ",
        "Xin lỗi em chỉ là con đĩ",
        "Yêu anh hơn cả tử thần",
        "Du Thái Hoa",
        "Mật ngọt hôn nhân",
        "Vạn kiếp yêu em",
        "Người đẹp phải mạnh mẽ",
        "Người anh yêu",
        "Nghe kìa thời gian đang hát",
        "Thành Duy Lạc",
        "Thiên kim đại chiến",
        "Trời đất tác thành",
        "Tường vi đêm đầu tiên",
        "Một nửa yêu thương",
        "Mandarin của tôi",
        "Gấu ơi giúp anh",
        "Em là vì sao trong mắt anh",
        "Sự dịu dàng chết tiệt",
        "Sổ tay hình cảnh",
        "Sẽ có thiên thần thay anh yêu em",
        "Quên để hạnh phúc",
        "Quân tử chi giao",
        "Phút giây gặp gỡ một đời bên nhau",
        "Cô bạn gái nhút nhát của tôi",
        "Cặp đôi hoàn cảnh",
        "Cửu thiên khuynh ca",
        "Xà vương quấn thân Bà xã sinh quả trứng",
        "Nàng dâu cực phẩm",
        "Nhất sinh nhất thế Tiếu Hồng Trần",
        "Sinh con thời mạt thế",
        "Hệ thống livestream của Nữ Đế",
        "Kế hoạch theo đuổi vợ yêu",
        "Chạy đâu cho thoát",
        "Bẫy hôn nhân Vợ trước ôm con chạy",
        "Chào buổi sáng Ông xã cool ngầu",
        "Thục thiên mộng hoa lục",
        "Liệt Hỏa Như Ca",
        "Bí mật vượt thời gian",
        "Xin em đứng đắn chút",
        "Bên nhau trọn đời",
        "Văn sĩ điên cuồng",
        "Đêm của anh ngày của em",
        "Giường đàn bà",
        "Hẹn ước nơi thiên đường",
        "Đại chiến mẹ chồng nàng dâu",
        "Mẹ chồng quyền thế của tôi",
        "Kết hôn chớp nhoáng",
        "Quân hôn chớp nhoáng",
        "Giây phút này thuộc về chúng ta",
        "Tình yêu bên trái",
        "Tình yêu điên cuồng",
        "Chỉ yêu cây kẹo bông nhỏ",
        "Tình yêu nơi đâu",
        "Thẻ đọc tâm",
        "Sự nhầm lẫn tai hại",
        "Mùa đông ấm áp",
        "Nhật ký chạy trốn tình yêu",
        "Thiên thần sa ngã",
        "Xem như anh lợi hại đồ xấu xa",
        "Bài học yêu của tiểu ma vương",
        "Trước là tiểu nhân sau là quân tử",
        "Không thể quên em",
        "Khi tình yêu đến lần nữa",
        "Tình yêu đau dạ dày",
        "Lễ tình nhân đến muộn",
        "Duyên nợ đào hoa",
        "Bài học yêu của tiểu ma vương",
        "Khách điếm Đại Long Môn",
        "Thái tử phi thăng chức ký",
        "Phiêu du giang hồ",
        "Năm tháng là đóa lưỡng sinh hoa",
        "Nhật ký dạy chồng của hổ cái",
        "Xem như anh lợi hại đồ xấu xa",
        "Ba kiếp dây dưa cửu vĩ hồ",
        "Một mối tương tư",
        "Chỉ vì phút giây được gặp em",
        "Nhất phẩm thiên kim",
        "Chạy đâu cho thoát",
        "Hôn nhân đã qua",
        "Thất dạ đàm",
        "Em là đôi cánh của anh",
        "Lan Lăng Vương",
        "Em đồng ý gọi anh là chồng",
        "Ảnh hậu tái sinh",
        "Tướng quân ở trên ta ở dưới",
        "Vì em gặp anh",
        "Hôn lên đôi môi Peter Pan",
        "Tháng ngày ta đã qua",
        "Ở lại nơi này cùng anh",
        "Hảo mộc vọng thiên",
        "Trầm Hương Uyển",
        "Đại thần em nuôi anh",
        "Boss hung mãnh 2 Cả đời chỉ vì em",
        "Không chỉ trong lời nói",
        "Thử ly hôn",
        "Nếu như có một ngày",
        "Dựa vào hơi ấm của em",
        "Mong rằng hoa vẫn đỏ",
        "Vận đào hoa của Tiểu Mật",
        "Hoài niệm",
        "Quyết ý đi cùng anh",
        "Nửa đường xuất giá",
        "Tình yêu còn mãi",
        "Cô chủ nhỏ xinh đẹp của tôi",
        "Boss là nữ phụ Thiên kim hào môn",
        "Không cẩn thận họa lớn rồi",
        "Nét cười nơi ấy",
        "Thất gia",
        "Dư vị trà chiều",
        "Boss hung mãnh Ông xã kết hôn nào",
        "Trăng đêm",
        "Hoài niệm",
        "Quán cà phê XY",
        "Nữ tặc Giang Bắc",
        "Bí mật vượt thời gian",
        "Chọc tức vợ yêu Mua một tặng một",
        "Yêu thương trao anh",
        "Hy du ký",
        "Này buông cô ấy ra",
        "Chuyện dũng cảm nhất",
        "Thiên Vương",
        "Hạnh phúc không ngừng",
        "Thùng cơm sát vách",
        "Thục thiên mộng hoa lục",
        "Ánh sao ban ngày",
        "Phấn hoa lầu xanh",
        "Hướng về trái tim",
        "Yêu em bằng cả trái tim anh",
        "Thành đô đêm nay hãy để tôi một mình",
        "Mị Hương",
        "Phiêu du giang hồ",
        "Hảo mộc vọng thiên",
        "Đại thần em nuôi anh",
        "Lập thệ thành yêu",
        "Dạo bước phồn hoa",
        "Nếu thanh xuân không giữ lại được",
        "Liên hoa yêu cốt",
        /*end*/
        "Một ai của ngày đó",
        "Dù yêu anh có lệch múi giờ",
        "Vụ án không có kẻ sát nhân",
        "Tên của trò chơi là bắt cóc",
        "Việc xấu",
        "Chấp dã",
        "Không ngờ idol lại yêu thầm tôi",
        "Bị ép gả cho nam thần",
        "Nhân cách nguy hiểm",
        "Ngoan liệt",
        "Xuyên thành cô út của đỉnh lưu showbiz",
        "Tổ điều tra đặc biệt",
        "Mỗi ngày tỉnh dậy đều biến thành kẻ tình nghi",
        "Siêu cấp cưng chiều",
        "Anh đến cùng ánh sao trời",
        "Tội ái",
        "Tịch Chiếu",
        "Phù Quang",
        "Nhân sinh mỹ học Một người sợ cô đơn hai người sợ phụ lòng",
        "Sự quyến rũ của tôi vô địch thiên hạ",
        "Lão tổ huyền môn bị ép trở thành thần",
        "Boss phản diện hàng ngày tìm đường chết",
        "Sống lại trở thành đại lão giới khoa học",
        "Niệm Tích",
        "Vụ án đảo Thỉ Nhạc",
        "Tôi có hào quang nữ chính",
        "Thì ra Boss thầm mến tôi",
        "Ấm quân",
        "Mỗi ngày chồng tôi diễn một vai",
        "Công chúa Las Vegas",
        "Những tội ác còn lẩn khuất",
        "Aliya đến thành phố Vô Cực",
        "Người tìm xác",
        "Số kiếp đã định trở thành vợ của Hoắc thiếu gia",
        "Hào môn thịnh sủng  Cô vợ minh tinh của tổng tài",
        "Cô ấy là nạn nhân",
        "Hệ thống quân trọng chấn phu cương",
        "Bờ biển điệp viên",
        "Đại yến nữ trừng phạt",
        "Xuyên nhanh Quỳ xuống cho mẹ",
        "Trọng sinh vào thập niên 80 vợ tôi là học bá",
        "Tướng quân xuất giá",
        "Đêm để lại dư âm",
        "Người dọn phòng",
        "Vị khách bí ẩn",
        "Hồ sơ dị án",
        "Ghi chú điều tra tội phạm của tôi",
        "Phu nhân áo choàng của em lại rơi rồi",
        "Tổ tông bùng nổ sau khi sống lại",
        "Cám dỗ ngọt ngào",
        "Y thê tam gả",
        "Dường như tinh trầm",
        "Thiếp trong lồng",
        "Vọng âm sau màn hình",
        "Hoa Thần Lục",
        "Nhật ký tra nam hoàn lương",
        "Gặp anh vào ngày tươi đẹp nhất",
        "Mật mã nước Cổ Thục",
        "Một ngày nọ tôi bỗng trở thành con gái nhà vua",
        "Nhân gian ngọc",
        "Tiên võ đế tôn",
        "Friendlist đỉnh nhất Tiên giới",
        "Tiên đế nhà ta đi ở rể rồi",
        "Hệ thống học bá vô địch",
        "Yêu nghiệt mạnh nhất",
        "Kiếm Vũ",
        "Lãnh cung phế hậu muốn nghịch thiên",
        "Hệ thống nhà ma",
        "Phục thiên thánh chủ",
        "Ôi sủng phi đại nhân của ta",
        "Cao thủ học đường",
        "Gia đinh hạng nhất",
        "Y Võ Chí Tôn",
        "Thiên tỉnh chi lộ",
        "Ta là đại tiên tôn",
        "Wechat của tôi là máy hack",
        "Xuyên không đến năm 3000",
        "Vị hôn phu từ trên trời rơi xuống",
        "Cấm vực huyết tộc",
        "Hành trình tìm lại kiếp trước",
        "Hệ thống ép ta làm hoàng hậu",
        "Nhật ký nuôi dưỡng thiếu nữ sói",
        "Từ hôm nay ta bắt đầu làm phú hộ",
        "Độc y đích nữ",
        "Hôn nhân ngọt ngào với băng sơn tổng tài",
        "Tổng tài ngây ngô yêu chiều cô vợ yêu",
        "Y đẳng cuồng binh",
        "Vạn giới tiên vương",
        "Vương gia xấu xa đừng trêu chọc ta",
        "Hóa ra ta là bệnh kiều",
        "Thơ tỏ tình chốn âm phủ",
        "Thượng quốc phú chi thiên đôi tuyết",
        "Hài Đế vi tôn",
        "Kiếm thần nghịch thiên",
        "Lão tổ tuyện thể mạnh nhất lịch sử",
        "Kịch giả thành thật",
        "Cực phẩm bại gia tử",
        "Long Đằng Chiến Tôn",
        "Thiên Ngoại Giang Hồ Đại Thần bỏ trốn của ta",
        "Thâu Thiên Hoán Nhật của Minh tướng quân",
        "Thiết lập nhân vật của minh chủ đáng yêu sụp đổ rồi",
        "Hứa với người vạn dặm sông núi",
        "Tuyệt sủng âm hôn",
        "Vương phi ngốc nghếch Bổn phi là đặc công khó nhằn",
        "Thái hậu bất lương trùng sinh",
        "Nha đầu biết trồng ruộng",
        "Kế hoạch sinh tồn của đích nữ Lấy trượng phu ngốc",
        "Quỷ giáng lâm Chồng ma thích trêu ghẹo",
        "Giam cầm vì yêu",
        "Trùng sinh bù đắp",
        "Mạt thế trùng sinh chi thụ quân đãng dạng sử",
        "Nữ phụ ở mạt thế",
        "Trầm hương tiết",
        "Lại trở thành phu nhân tướng quân",
        "Trùng sinh làm giàu ở cổ đại",
        "Một đời yêu chiều",
        "Mười dặm gió xuân không bằng yêu anh",
        "Trùng sinh chi trêu chọc",
        "Quyến rũ ông chú tuổi băm",
        "Nữ phụ trở mình",
        "Cám dỗ ngọt ngào",
        "Tình yêu của pháo hôi",
        "Trùng sinh chi cẩm tú (Gấm vóc trùng sinh)",
        "Hôn nhân trời định",
        "Yêu em bằng cả trái tim",
        "Yêu lại từ đầu",
        "Chồng yêu khó chiều",
        "Nợ âm phải trả",
        "Duyên âm nửa đêm quỷ phu xin hãy nhẹ nhàng",
        "Công sói thụ hồ ly",
        "Lục Thâm",
        "Ngủ cùng sói",
        "Hoắc gia phu nhân lại đi xem bói rồi",
        "Giả ngoan",
        "Phò mã là nghề nguy hiểm",
        "Nhật ký mối tình đầu của Ngư tiểu thư",
        "Vợ yêu nhà thủ trưởng",
        "Dụ hôn",
        "Cô vợ hung tàn của Quyền thiếu",
        "Trùng sinh tôi nhặt được chàng cơ trưởng",
        "Vợ tôi là trùm cuối",
        "Lưu manh đi lấy vợ",
        "Thế tử phi cá muối",
        "Kim Phấn",
        "Tân An Quỷ Sự",
        "Nhật ký làm ruộng ở thôn Trường Thủy",
        "Ôn nhu vượt rào",
        "Hoàng hậu bất lương mê hoặc quân tâm",
        "Chúa tể trở về",
        "Đưa em ra khỏi hố sâu đầm lầy",
        "Nếu khi đông về gặp hạ ấm",
        "Cấp trên trở thành kim chủ của tôi",
        "Hôm nay lại tán tỉnh hệ thống",
        "Tình thâm không bằng mối hận xưa",
        "Tổng tài vs Trạch nữ",
        "Cao thủ hàng đầu của nữ Boss",
        "Bỗng dưng được sủng",
        "Tuyệt thế cổ tôn",
        "Điệp ảnh trùng trùng",
        "Tà vương nham hiểm Cưng chiều tận xương",
        "Chị gái ơi không phải như chị nghĩ đâu",
        "Bảo bối tiểu thanh mai",
        "Đám cưới bí mật",
        "Hỗn độn Kim Ô",
        "Daddy nam thần của Tiểu Bạch",
        "Báo cáo Đế Quân ngài có độc",
        "Chồng ơi em muốn ăn cho anh sạt nghiệp",
        "Nghịch tập trở về Cô vợ vô dụng của tôi",
        "Hôn sắc liêu nhân",
        "Nhặt boss về làm ông xã",
        "Tôi sẽ không yêu bạn gái hợp đồng đâu",
        "Thiếu chủ hung dữ quá ta thích lắm",
        "Tiểu thư thỏ của tổng giám đốc sói",
        "Ác nữ vai phụ Khúc nhạc theo đuổi tình yêu",
        "Tuyệt sắc y nữ Thái tử à ngài thuận theo ta đi",
        "Muốn ngủ cùng em",
        "Cuộc chiến tái hôn Trường kì theo đuổi vợ",
        "Vương phi thần trộm Vương gia nhà ta không dễ chọc",
        "Vợ yêu nham hiểm của Cơ thiếu",
        "Mỹ nam dị giới ngã vào lòng ta",
        "Chọc giận cuồng phi Vương gia sủng ái điên cuồng",
        "Phúc hắc vương gia Cô vợ bị bỏ rơi không dễ chọc",
        "Đế tôn cuồng sủng Đặc công thần y",
        "Tổng tài xấu xa đừng làm loạn",
        "Theo đuổi em khắp thế gian",
        "Ông xã ma cà rồng",
        "Thư ký riêng của tổng tài",
        "Hi tên của ta là Liêm",
        "Quốc sư đại nhân liêm sỉ của ngài đâu rồi?",
        "Vương gia muốn động phòng",
        "Kiều thê được cưng chiều của tổng tài",
        "Linh lung lang tâm",
        "Hôn ước hào môn Phu nhân tổng tài thật điên cuồng",
        "Giấu đầu hở đuôi",
        "Em gái ranh ma không dễ chọc",
        "Ác ma bên gối",
        "Một đêm chưa hết tình Tổng tài đừng quá hư",
        "Họa phi thời loạn",
        "Ông chồng xấu xa Độc sủng vợ yêu",
        "Chủ tịch lạnh lùng muốn độc chiếm tôi",
        "Chuyến tàu ma quái",
        "Hoàng tử là bảo mẫu",
        "Gia tộc lừa đảo",
        "Trò chơi tình yêu Đồ chơi của ác ma",
        "Cô vợ bạc tỷ của Mặc Thiếu",
        "Tổng tài ác ma Bảo bối ngọt ngào mau đầu hàng",
        "Chọc nhầm tổng tài hào môn",
        "Y Phi cầm quyền",
        "Tiến hóa thần chủng",
        "Thầy giáo kỳ lạ",
        "Ngựa của trẫm là hồ ly tinh",
        "Hoàn khố vương phi muốn trèo tường",
        "Tân nương gả thay của tổng tài",
        "Kết hôn chớp nhoáng",
        "Chí mạng sủng thê Tổng tài anh xong đời rồi",
        "Sống chung với bạn trai ngôi sao",
        "Tiên đế nghịch thiên",
        "Vương bài thần côn",
        "Đặc công vương phi ngược cặn bã",
        "Lãnh ngạo thần y 36 kế sủng phu",
        "Sắp bị ác long xơi tái",
        "Vương phi lại tán tỉnh ta rồi",
        "Vương phi hung hãn",
        "Hoàng tử phu quân để ta nuôi chàng",
        "Ông xã quân phiệt xấu xa Bá đạo chiếm lấy em",
        "Bóng hình của gió",
        "Bạn trai hắc đạo của tôi",
        "Thôn y háo sắc",
        "Cô vợ nhỏ bí ẩn của Boss",
        "Chuyện tình nàng yêu tinh",
        "Chung cư xuân sắc tràn đầy",
        "Lừa hôn đế thiếu Cô dâu nhỏ ngọt ngào",
        "Tiên kiếm Minh Nhạc",
        "Danh môn kinh hôn Cố thiếu anh đủ rồi",
        "Rung cảm từ em",
        "Yêu em bằng cả sinh mệnh",
        "Vợ yêu là đại lão",
        "Bỉ Ngạn đơm hương",
        "Ti quân đòi mệnh",
        "Trêu chọc vượt giới",
        "Dệt ngân hà cho em",
        "Bài thi ma quỷ",
        "Nhân gian không sánh bằng em",
        "Cẩm hương lí",
        "Siêu phẩm xuyên thấu",
        "Tiên phong kiếm vũ lục",
        "Yêu thần ký",
        "Tinh võ thần quyết",
        "Chúa tể võ thần",
        "Vạn giới tiên tông",
        "Kiến Phệ Long",
        "Nhiễm sắc thể số 47",
        "Vạn giới thần chủ",
        "Con mắt X quang",
        "Tuyệt thế yêu đế",
        "Cô vợ gả thay của thiếu gia",
        "Võ đạo độc tôn",
        "Diệu thủ cuồng y",
        "Danh môn thiên hậu",
        "Tiểu thư đỏng đảnh PK Thiếu gia bá đạo",
        "Điện hạ ma cà rồng thân yêu",
        "Lừa gạt thiếu gia quý tộc làm bạn trai",
        "Bảo bối ngây thơ của tà thiếu",
        "Nhà có cô vợ dữ",
        "Cô vợ thiên kim",
        "Boss lạnh lùng hãy buông tay",
        "PK đi Vương gia",
        "Dị năng thiếu niên vương",
        "Chúa cứu thế trạch nam",
        "Đặc công ngự dụng",
        "Chưởng môn 18 tuổi",
        "NPC mạnh nhất",
        "Bạn trai không tồn tại",
        "Chủ nhà yêu quái tránh xa tôi ra",
        "Nam thần của tôi biến thân rồi",
        "Viên lão quái kỳ án",
        "Người dấu yêu",
        "Chỉ yêu mình em",
        "Doanh môn phục quý",
        "Hệ thống nhà ma",
        "Quỷ giấu người",
        "Bùi Thái Thái đã kết hôn",
        "Tên anh là thời gian",
        "Pháo hôi ư ư đại lão",
        "Ta là miêu đại vương",
        "Nếu có thể làm lại lần nữa",
        "Phương trình thanh xuân chờ giải",
        "Cô vợ diễn viên của Cố thiếu",
        "Quán cà phê mèo",
        "Tội ác vô hình",
        "Chị ơi đưa em về cùng",
        "Nam thành đãi nguyệt quy",
        "Thành Nam sóng gió chưa tan",
        "Nghe nói Lục Chi Cửu yêu tôi đã nhiều năm",
        "Viết cho tiên sinh Yển Thử (chuột chũi) một lá thư tình",
        "Người thiếu niên tóc xanh mềm",
        "Hoán đổi linh hồn",
        "Thanh quỷ kỷ sự",
        "Anh đến cùng ánh sao trời",
        "Thoát xác",
        "Giường anh chia em một nửa",
        "Hành Tẩu Âm Dương",
        "Hoàng Hà Phục Yêu Truyện",
        "Cách một cánh cửa",
        "Mộ Khâu Tử",
        "Thầy dời mộ",
        "Đời ấm áp khi có em ngọt ngào khi có anh",
        "Đặc công vườn trường",
        "Nhất nộ thành tiên",
        "Âu thần",
        "Đồ đệ nhà ta lại tèo rồi",
        "Tam thốn nhân gian",
        "Xin chào thiếu tướng đại nhân",
        "Gió ấm không bằng anh thâm tình",
        "Duy nhất là em",
        "Siêu thần cơ giới sư",
        "Thanh xuân bắt đầu từ khi gặp anh",
        "Tu chân liêu thiên quần",
        "Siêu cấp gen thần",
        "Thiên Hậu Trở Về",
        "Bảo bối giá trên trời",
        "Khu vui chơi đáng sợ",
        "Triệu hoán mộng yểm",
        "Bậc thầy thẻ bài",
        "Quậy Tung Hogwarts",
        "Phúc Hán",
        "Tôi là trùm đứng sau màn",
        "Thời đại game quật khởi",
        "Luận kiếm toàn cầu",
        "Hệ thống quán net",
        "Đặc công Maver",
        "Nhà hàng dị giới của ông bố bỉm sữa",
        "Cuộc đổ bộ của Pokemon",
        "Chicago 1990",
        "Ngài cố thân mến",
        "Em là cả nhân gian của anh",
        "Hotboy ác ma ăn sạch cô bé ngọt ngào",
        "Cục cưng ôm cái nào",
        "Thiên hậu tiểu thanh mai",
        "Y phẩm phong hoa",
        "Tiểu thư thần toán",
        "Thiên kim báo thù",
        "Nam thần khó theo đuổi",
        "Tiên Tôn lại trêu chọc ta",
        "Thịnh Thế Kiều Y",
        "Người trong mộng",
        "Phi tử điên cuồng Huyễn linh sư cực phẩm",
        "Bạn gái tôi là mèo",
        "Nhiếp huyết ngọc kỳ án thời Đường",
        "Cửa tiệm trường sinh",
        "Mỹ nhân quạt hợp hoan",
        "Yêu đương không đứng đắn",
        "Hoàng đế chỉ muốn độc thân",
        "Nghề làm mẹ",
        "Sổ tay tâm thần phân liệt",
        "Điệp viên kỳ quái",
        "Huống hồ tuổi xuân đang tàn úa",
        "Gái già muốn lấy chồng",
        "Hoa hồng trắng",
        "Sơ Cửu của Lục Hào",
        "Văn phòng Phấn Hồng",
        "Truy tìm bóng đêm",
        "Ấn Công Đức",
        "Ảnh đế thị phi",
        "Khi tương tư hóa tro tàn",
        "Hắc thiên kim",
        "Phòng cấp cứu",
        "Chiến thần Địch Thanh",
        "Vua mua sắm tam giới",
        "Hội chứng không kết hôn",
        "Cửa hàng vịt giang hồ",
        "Uông Xưởng Công",
        "Xuyên nhanh Nam thần chạy theo nữ phụ mất rồi",
        "Dược sư trùng sinh năm 1979",
        "Nông nữ Trân Châu",
        "Mạt thế Phượng hoàng trở về",
        "Cuộc sống làm màu của nam thần",
        "Bạn gái tâm thần của cảnh sát trưởng",
        "Cái bẫy dài hơi của ảnh đế",
        "Tán tôi đi rồi tôi đổ",
        "Chân chó của đại thần",
        "Cẩm Đường Quy Yến",
        "Quân hôn chớp nhoáng",
        "Nông Viên Tự Cẩm",
        "Cưng chiều cô vợ đanh đá",
        "Thịnh thế hôn nhân",
        "Lấy chồng quyền thế",
        "Hứa với em một đời hoa nở",
        "Điền viên cẩm tú",
        "Thực tập sinh Thần Tượng",
        "Nhật ký sa lầy",
        "Gặp đúng lúc yêu đúng người",
        "Chuyện tình học viện tinh tế",
        "Tiểu thư hầu phủ",
        "Nhật ký trở thành boss thời mạt thế",
        "Quân hôn chớp nhoáng",
        "Bí mật thiên kim",
        "Vợ Boss không online",
        "Nữ hoàng màn ảnh",
        "Hậu chiến chốn thâm cung",
        "Độc phụ không hoàn lương",
        "Sổ tay ngược cặn bã của đích nữ",
        "Cưng chiều cô vợ quân nhân",
        "Nhặt được vương phi tham tiền",
        "Đám cưới hào môn",
        "Tình đắng",
        "Bách luyện thành thần",
        "Cuồng thám",
        "Thư viện Thiên Đạo",
        "Nhật ký cua trai của nữ phụ",
        "Nhật ký tu tiên của nữ phụ",
        "Thú trấn mộ",
        "Bổ thiên ký",
        "Trình Sinh",
        "Tiên Sư làm Vườn",
        "Nhật ký trưởng thành của Nữ Oa",
        "Tình nhân đẳng cấp thế giới",
        "Nàng dâu cực phẩm",
        "Mật ngọt hôn nhân",
        "Vợ Boss là công chúa",
        "Xà vương quấn thân Bà xã sinh quả trứng",
        "Nhất sinh nhất thế tiếu hồng trần",
        "Phượng kinh thiên",
        "Vương phủ mỗi ngày gà bay chó chạy",
        "Người tìm xác",
        "Đông Phương thần thám",
        "Công tước",
        "Nhất sinh nhất thế tiếu thương khung",
        "Kế hoạch theo đuổi vợ yêu",
        "Hello người thừa kế",
        "Nhật ký tiểu hoà thượng ở thành phố",
        "Sinh con thời mạt thế",
        "Hệ thống phát sóng trực tiếp của Nữ Đế",
        "Boss hung mãnh Ông xã kết hôn nào",
        "Chọc tức vợ yêu Mua một tặng một",
        "Boss là nữ phụ",
        "Hồ sơ bí ẩn",
        "Dạo bước phồn hoa",
        "Chào buổi sáng ông xã cool ngầu",
        "Bẫy hôn nhân vợ trước ôm con chạy",
        "Boss hung mãnh 2 Cả đời chỉ vì em"
    ];

    try {
        // Chuẩn hoá chung: hạ chữ, bỏ dấu tiếng Việt, xoá khoảng trắng & ký tự đặc biệt
        const norm = (s) =>
            (s ?? "")
            .toLowerCase()
            .normalize("NFD")                 // tách dấu
            .replace(/\p{M}/gu, "")           // xoá dấu (unicode marks)
            .replace(/[\s\-\.,!?:'\"()\[\]{}<>`~@#$%^&*_\+=\/\\|]/g, ""); // xoá ký tự

            // Dùng Set để tra nhanh O(1)
        const blackSet = new Set(blackList.map(norm));

        let novelList = [];
        let nextElement = document.querySelector(".pagination > li.active + li");
        let next = nextElement ? nextElement.textContent.trim() : null;
        if (!next) { next = 0;}
        else { next = Number(next); }

        document.querySelectorAll(".list-truyen div[itemscope]").forEach(e => {
            const name = e.querySelector(".truyen-title > a")?.textContent.trim();
            const nameCmp = norm(name);

            // kiểm tra blacklist
            if (nameCmp && !blackSet.has(nameCmp)) {
                novelList.push({
                    name: name,
                    link: e.querySelector(".truyen-title > a")?.href,
                    description: e.querySelector(".author")?.textContent.trim(),
                    cover: e.querySelector("[data-image]")?.getAttribute("data-image"),
                    host: "https://truyenfull.vision"
                });
            }
        });

        return JSON.stringify({ success: true, data: novelList, next: next });
    } catch (error) {
        return JSON.stringify({ success: false, error: error.message });
    }
})()
